version: "3.9"

services:
  rasa:
    image: rasa/rasa:3.6.8
    container_name: rasa_server
    volumes:
      - ./:/app
    ports:
      - "5005:5005"
    command: >
      run --enable-api --cors "*"

  actions:
    image: rasa/rasa-sdk:3.6.2
    container_name: rasa_actions
    volumes:
      - ./actions:/app/actions
    ports:
      - "5055:5055"

  llm_service:
    image: satvik1945/llm_service:latest
    container_name: llm_service
    ports:
      - "8000:8000"

  mongo:
    image: mongo:6.0
    container_name: mongo_db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: